dependencies:
  - name: mongodb
    version: 4.2.18
    repository: file://../mongodb
  - name: rabbitmq
    version: 1.0.0
    repository: file://../rabbitmq
  - name: crawler-bot
    version: 1.0.0
    repository: file://../crawler
  - name: crawler-ui
    version: 1.0.0
    repository: file://../ui
