---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ui.fullname" . }}
  namespace: app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.internalPort }}"
    prometheus.io/path: "/metrics"
  labels:
    app: search_engine
    component: ui
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: search_engine
      component: ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler-ui
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.internalPort }}"
        prometheus.io/path: "/metrics"
      labels:
        app: search_engine
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: ui
        env:
          - name: MONGO
            value:  '{{ .Values.MONGO | default (printf "mongodb") }}'
          - name: MONGO_PORT
            value:  '{{ .Values.MONGO_PORT | default (printf "27017" ) }}'
