---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: search_engine
    component: ui
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: search_engine
      component: ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler-ui
      labels:
        app: search_engine
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: ui
        env:
          - name: MONGO
            value:  '{{ .Values.MONGO | default (printf "%s-mongodb" .Release.Name) }}'
          - name: MONGO_PORT
            value:  '{{ .Values.MONGO_PORT | default (printf "27017" ) }}'
