---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
  namespace: app
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - host: app.vlashm.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Chart.Name }}
                port: 
                  number: {{ .Values.service.externalPort }}