---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: search_engine
    component: ui
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: {{ .Values.service.externalPort }}
     targetPort: {{ .Values.service.internalPort }}
  selector:
    app: search_engine
    component: ui
    release: {{ .Release.Name }}
