---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  namespace: app
  labels:
    app: search_engine
    component: crawler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search_engine
      component: crawler
  template:
    metadata:
      name: crawler
      labels:
        app: search_engine
        component: crawler
    spec:
      containers:
      - name: crawler
        image: vlashm/crawler:latest
        env:
          - name: MONGO
            value: server-mongodb
          - name: MONGO_PORT
            value: "27017"
          - name: RMQ_HOST
            value: rabbitmq
          - name: RMQ_QUEUE
            value: crawler
          - name: RMQ_USERNAME
            value: user
          - name: RMQ_PASSWORD
            value: user_pass
          - name: CHECK_INTERVAL
            value: "10"
          - name: EXCLUDE_URLS
            value: '.*github.com'