---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  namespace: app
  labels:
    app: search_engine
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: rabbitmq
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "rabbitmq.fullname" . }}
      labels:
        app: search_engine
        component: rabbitmq
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ template "rabbitmq.fullname" . }}
        env:
        # - name: RMQ_PORT_INT
        #   value: '{{  .Values.rmq_portint | default "15672"}}'
        # - name: RMQ_PORT
        #   value: '{{  .Values.rmq_port | default "5672"}}'
        - name: RABBITMQ_USERNAME
          value: '{{  .Values.rmq_username | default (printf "user") }}'
        - name: RABBITMQ_PASSWORD
          value: '{{  .Values.rmq_password | default (printf "user_pass") }}'