---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  namespace: app
  labels:
    app: search_engine
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 15672
    - name: amqp
      protocol: TCP
      port: 5672
  selector:
    app: search_engine
    component: rabbitmq
    release: {{ .Release.Name }}
