---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: app
  labels:
    app: search_engine
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app: search_engine
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: bitnami/rabbitmq
        env:
        - name: RABBITMQ_USERNAME
          value: user
        - name: RABBITMQ_PASSWORD
          value: user_pass
