---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  namespace: app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.internalPort }}"
    prometheus.io/path: "/metrics"
  labels:
    app: search_engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: search_engine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.internalPort }}"
        prometheus.io/path: "/metrics"
      labels:
        app: search_engine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        env:
          - name: MONGO
            value:  '{{ .Values.MONGO | default (printf "mongodb") }}'
          - name: MONGO_PORT
            value: '{{ .Values.MONGO_PORT | default (printf "27017") }}'
          - name: RMQ_HOST
            value: '{{ .Values.RMQ_HOST | default (printf "rabbitmq") }}'
          - name: RMQ_QUEUE
            value: '{{ .Values.RMQ_QUEUE | default (printf "crawler") }}'
          - name: RMQ_USERNAME
            value: '{{ .Values.RMQ_USERNAME | default (printf "user") }}'
          - name: RMQ_PASSWORD
            value: '{{ .Values.RMQ_PASSWORD | default (printf "user_pass") }}'
          - name: CHECK_INTERVAL
            value: '{{ .Values.CHECK_INTERVAL | default (printf "10" )}}'
          - name: EXCLUDE_URLS
            value: '{{ .Values.EXCLUDE_URLS | default (printf ".*github.com") }}'