---
apiVersion: v1
kind: Service
metadata:
  name: server-mongodb
  namespace: app
  labels:
    app: search_engine
    component: mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: search_engine
    component: mongodb