---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mongodb.fullname" . }}
  namespace: app
  labels:
    app: search_engine
    component: mongodb
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: mongodb
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "mongodb.fullname" . }}
      labels:
        app: search_engine
        component: mongodb
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ template "mongodb.fullname" . }}
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
      volumes:
      - name: mongodb
        emptyDir: {}