---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb.fullname" . }}
  namespace: app
  labels:
    app: search_engine
    component: mongodb
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: search_engine
    component: mongodb
    release: {{ .Release.Name }}
